release:
  github:
    owner: Matt-Gleich
    name: 'ctree'
  prerelease: auto
before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
